# Generated by Django 3.2.19 on 2025-05-25 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversiones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inversion',
            name='tipo_inversion',
            field=models.CharField(choices=[('ahorro', 'Ahorro'), ('cripto', 'Criptomoneda'), ('bienes', 'Bienes Raíces'), ('otro', 'Otro')], default='otro', max_length=20),
        ),
    ]
